# Generated by Django 4.0.4 on 2022-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_main', models.CharField(max_length=100)),
                ('lname_main', models.CharField(max_length=100)),
                ('email_main', models.CharField(max_length=100)),
                ('phone_main', models.CharField(max_length=100)),
                ('bday_main', models.DateTimeField(verbose_name='bday of main user')),
                ('country_main', models.CharField(max_length=100)),
                ('gender_main', models.CharField(max_length=100)),
                ('user_main', models.CharField(max_length=100)),
                ('pass_main', models.CharField(max_length=100)),
                ('edit_main', models.DateTimeField(verbose_name='date edited')),
                ('create_main', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
